using UnityEngine;

public class CraftObject : MonoBehaviour
{
    [SerializeField] private Crafting혀tegory _crafting혀tegory;
    [SerializeField] private CraftingHandler _craftingHandler;

    private void OnTriggerEnter(Collider other)
    {
        if (other.TryGetComponent(out ManualWorkbench manualWorkbench))
        {
            _craftingHandler.DisplayCraftWindow(_crafting혀tegory);
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.TryGetComponent(out ManualWorkbench manualWorkbench))
        {
            _craftingHandler.DisplayCraftWindow(manualWorkbench.Crafting혀tegory);
        }
    }
}
